"""add elearning sql api models

Revision ID: 1b9137dfd4ac
Revises: 5e5c85f48480
Create Date: 2026-08-24 22:15:33.095734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b9137dfd4ac'
down_revision = '5e5c85f48480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_playlists',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail', sa.Text(), nullable=True),
    sa.Column('thumbnail_file_name', sa.String(length=500), nullable=True),
    sa.Column('course_ids', sa.JSON(), nullable=False),
    sa.Column('playlist_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_playlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_playlists_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_playlists_owner_id'), ['owner_id'], unique=False)

    op.create_table('elearning_notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_data', sa.JSON(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('elearning_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_elearning_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_elearning_notifications_dismissed'), ['dismissed'], unique=False)
        batch_op.create_index(batch_op.f('ix_elearning_notifications_legacy_id'), ['legacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_elearning_notifications_read'), ['read'], unique=False)
        batch_op.create_index(batch_op.f('ix_elearning_notifications_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_elearning_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('user_follows',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('follower_id', sa.BigInteger(), nullable=False),
    sa.Column('target_user_id', sa.BigInteger(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('follow_data', sa.JSON(), nullable=False),
    sa.Column('followed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unfollowed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'target_user_id', name='uq_user_follows_follower_target')
    )
    with op.batch_alter_table('user_follows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_follows_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_follows_follower_id'), ['follower_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_follows_target_user_id'), ['target_user_id'], unique=False)

    op.create_table('comment_warnings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('issued_by', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=True),
    sa.Column('question_id', sa.BigInteger(), nullable=True),
    sa.Column('reply_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('warning_data', sa.JSON(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['course_questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reply_id'], ['course_question_replies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment_warnings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_warnings_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_warnings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_warnings_issued_by'), ['issued_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_warnings_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_warnings_reply_id'), ['reply_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_warnings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_warnings_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_warnings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_warnings_user_id'))
        batch_op.drop_index(batch_op.f('ix_comment_warnings_status'))
        batch_op.drop_index(batch_op.f('ix_comment_warnings_reply_id'))
        batch_op.drop_index(batch_op.f('ix_comment_warnings_question_id'))
        batch_op.drop_index(batch_op.f('ix_comment_warnings_issued_by'))
        batch_op.drop_index(batch_op.f('ix_comment_warnings_created_at'))
        batch_op.drop_index(batch_op.f('ix_comment_warnings_course_id'))

    op.drop_table('comment_warnings')
    with op.batch_alter_table('user_follows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_follows_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_follows_follower_id'))
        batch_op.drop_index(batch_op.f('ix_user_follows_active'))

    op.drop_table('user_follows')
    with op.batch_alter_table('elearning_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_elearning_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_elearning_notifications_type'))
        batch_op.drop_index(batch_op.f('ix_elearning_notifications_read'))
        batch_op.drop_index(batch_op.f('ix_elearning_notifications_legacy_id'))
        batch_op.drop_index(batch_op.f('ix_elearning_notifications_dismissed'))
        batch_op.drop_index(batch_op.f('ix_elearning_notifications_created_at'))

    op.drop_table('elearning_notifications')
    with op.batch_alter_table('course_playlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_playlists_owner_id'))
        batch_op.drop_index(batch_op.f('ix_course_playlists_created_at'))

    op.drop_table('course_playlists')
    # ### end Alembic commands ###
