"""add forum reports

Revision ID: 1e7237cbec13
Revises: be588aa4e89a
Create Date: 2026-08-24 16:16:37.013707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e7237cbec13'
down_revision = 'be588aa4e89a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('post_title', sa.String(length=255), nullable=True),
    sa.Column('post_content', sa.Text(), nullable=True),
    sa.Column('post_author_id', sa.BigInteger(), nullable=True),
    sa.Column('post_author_name', sa.String(length=255), nullable=True),
    sa.Column('reporter_id', sa.BigInteger(), nullable=False),
    sa.Column('reporter_name', sa.String(length=255), nullable=True),
    sa.Column('reporter_email', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resolved_by', sa.BigInteger(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['forum_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'reporter_id', name='uq_forum_reports_post_reporter')
    )
    with op.batch_alter_table('forum_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_reports_post_author_id'), ['post_author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_reports_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_reports_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_reports_scope'), ['scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_reports_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_reports_status'))
        batch_op.drop_index(batch_op.f('ix_forum_reports_scope'))
        batch_op.drop_index(batch_op.f('ix_forum_reports_reporter_id'))
        batch_op.drop_index(batch_op.f('ix_forum_reports_post_id'))
        batch_op.drop_index(batch_op.f('ix_forum_reports_post_author_id'))
        batch_op.drop_index(batch_op.f('ix_forum_reports_created_at'))

    op.drop_table('forum_reports')
    # ### end Alembic commands ###
