"""add e-learning models

Revision ID: 4419cca4d1e4
Revises:
Create Date: 2026-08-23 20:55:02.539294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4419cca4d1e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('class_code', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classrooms_class_code'), ['class_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_classrooms_grade'), ['grade'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('class_name', sa.String(length=100), nullable=True),
    sa.Column('google_sub', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('STUDENT', 'TEACHER', 'ADMIN_DEV')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_class_name'), ['class_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_google_sub'), ['google_sub'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_grade'), ['grade'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('chat_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_conversations_user_id'), ['user_id'], unique=True)

    op.create_table('course_saved_lists',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail', sa.Text(), nullable=True),
    sa.Column('thumbnail_file_name', sa.String(length=500), nullable=True),
    sa.Column('list_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_saved_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_saved_lists_owner_id'), ['owner_id'], unique=False)

    op.create_table('courses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=255), nullable=True),
    sa.Column('teacher_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('topic', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('thumbnail', sa.Text(), nullable=True),
    sa.Column('thumbnail_file_name', sa.String(length=500), nullable=True),
    sa.Column('document_image_url', sa.Text(), nullable=True),
    sa.Column('document_image_name', sa.String(length=500), nullable=True),
    sa.Column('document_image_size', sa.BigInteger(), nullable=False),
    sa.Column('document_file_size', sa.BigInteger(), nullable=False),
    sa.Column('word_file_name', sa.String(length=500), nullable=True),
    sa.Column('word_file_url', sa.Text(), nullable=True),
    sa.Column('rich_document', sa.Text(), nullable=True),
    sa.Column('document_mode', sa.String(length=100), nullable=True),
    sa.Column('document_file_type', sa.String(length=100), nullable=True),
    sa.Column('simulation_mode', sa.String(length=100), nullable=True),
    sa.Column('simulation_url', sa.Text(), nullable=True),
    sa.Column('simulation_html', sa.Text(), nullable=True),
    sa.Column('simulation_language', sa.String(length=100), nullable=True),
    sa.Column('simulation_code', sa.Text(), nullable=True),
    sa.Column('simulation_codes', sa.JSON(), nullable=False),
    sa.Column('simulation_instructions', sa.Text(), nullable=True),
    sa.Column('youtube_url', sa.Text(), nullable=True),
    sa.Column('lumi_url', sa.Text(), nullable=True),
    sa.Column('mp4_file_name', sa.String(length=500), nullable=True),
    sa.Column('mp4_file_url', sa.Text(), nullable=True),
    sa.Column('video_source_type', sa.String(length=100), nullable=True),
    sa.Column('video_sources', sa.JSON(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('youtube_duration', sa.String(length=100), nullable=True),
    sa.Column('attach_mode', sa.String(length=100), nullable=True),
    sa.Column('code_language', sa.String(length=100), nullable=True),
    sa.Column('code_content', sa.Text(), nullable=True),
    sa.Column('learning_objectives', sa.JSON(), nullable=False),
    sa.Column('prerequisites', sa.JSON(), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('checklist', sa.JSON(), nullable=False),
    sa.Column('quiz', sa.JSON(), nullable=False),
    sa.Column('lesson_topics', sa.JSON(), nullable=False),
    sa.Column('lessons', sa.JSON(), nullable=False),
    sa.Column('lesson_count', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=255), nullable=True),
    sa.Column('teacher_code', sa.String(length=255), nullable=True),
    sa.Column('teacher_email', sa.String(length=255), nullable=True),
    sa.Column('teacher_name', sa.String(length=255), nullable=True),
    sa.Column('teacher_subject', sa.String(length=255), nullable=True),
    sa.Column('created_by_role', sa.String(length=50), nullable=True),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('class_id', sa.String(length=255), nullable=True),
    sa.Column('class_name', sa.String(length=255), nullable=True),
    sa.Column('open_at', sa.String(length=255), nullable=True),
    sa.Column('open_at_ms', sa.BigInteger(), nullable=True),
    sa.Column('publish_confirmed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('moderation_status', sa.String(length=50), nullable=False),
    sa.Column('student_count', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('rating_total', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_class_name'), ['class_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_content_type'), ['content_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_course_code'), ['course_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_courses_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_is_featured'), ['is_featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_legacy_id'), ['legacy_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_courses_moderation_status'), ['moderation_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_open_at_ms'), ['open_at_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_teacher_email'), ['teacher_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_teacher_id'), ['teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_teacher_subject'), ['teacher_subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_visibility'), ['visibility'], unique=False)

    op.create_table('exams',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('visibility', sa.String(length=50), nullable=True),
    sa.Column('selected_grades', sa.JSON(), nullable=False),
    sa.Column('selected_classes', sa.JSON(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('student_result_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exams_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_exams_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_exams_teacher_id'), ['teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exams_visibility'), ['visibility'], unique=False)

    op.create_table('course_questions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=255), nullable=True),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('user_avatar', sa.Text(), nullable=True),
    sa.Column('user_role', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('question_data', sa.JSON(), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_questions_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_questions_legacy_id'), ['legacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_questions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_questions_user_role'), ['user_role'], unique=False)

    op.create_table('course_ratings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'user_id', name='uq_course_rating_user')
    )
    with op.batch_alter_table('course_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_ratings_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_ratings_user_id'), ['user_id'], unique=False)

    op.create_table('course_saved_list_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('saved_list_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['saved_list_id'], ['course_saved_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('saved_list_id', 'course_id', name='uq_saved_list_course')
    )
    with op.batch_alter_table('course_saved_list_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_saved_list_items_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_saved_list_items_saved_list_id'), ['saved_list_id'], unique=False)

    op.create_table('course_views',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('first_viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('view_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'user_id', name='uq_course_view_user')
    )
    with op.batch_alter_table('course_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_views_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_views_user_id'), ['user_id'], unique=False)

    op.create_table('exam_attempts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('attempt_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'student_id', name='uq_exam_attempt_student')
    )
    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_attempts_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_attempts_student_id'), ['student_id'], unique=False)

    op.create_table('exam_questions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.BigInteger(), nullable=False),
    sa.Column('question_key', sa.String(length=255), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('question_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'question_key', name='uq_exam_question_key')
    )
    with op.batch_alter_table('exam_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_questions_exam_id'), ['exam_id'], unique=False)

    op.create_table('exam_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_results_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_results_student_id'), ['student_id'], unique=False)

    op.create_table('learning_progress',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('watched_seconds', sa.Integer(), nullable=False),
    sa.Column('watched_date', sa.String(length=20), nullable=True),
    sa.Column('bookmarked', sa.Boolean(), nullable=False),
    sa.Column('completed_checklist', sa.JSON(), nullable=False),
    sa.Column('quiz_result', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('note_color', sa.String(length=50), nullable=True),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_watched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_watched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unsaved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_learning_progress_user_course')
    )
    with op.batch_alter_table('learning_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_progress_bookmarked'), ['bookmarked'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_progress_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_progress_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_progress_watched_date'), ['watched_date'], unique=False)

    op.create_table('proctoring_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('session_key', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('violation_count', sa.Integer(), nullable=False),
    sa.Column('session_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proctoring_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proctoring_sessions_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proctoring_sessions_session_key'), ['session_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_proctoring_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_proctoring_sessions_student_id'), ['student_id'], unique=False)

    op.create_table('course_question_replies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=255), nullable=True),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('user_avatar', sa.Text(), nullable=True),
    sa.Column('user_role', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_teacher_reply', sa.Boolean(), nullable=False),
    sa.Column('reply_data', sa.JSON(), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['course_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_question_replies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_question_replies_legacy_id'), ['legacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_question_replies_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_question_replies_user_id'), ['user_id'], unique=False)

    op.create_table('proctoring_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('event_data', sa.JSON(), nullable=False),
    sa.Column('server_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['proctoring_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proctoring_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proctoring_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_proctoring_events_session_id'), ['session_id'], unique=False)

    op.create_table('learning_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('reporter_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=True),
    sa.Column('reported_user_id', sa.BigInteger(), nullable=True),
    sa.Column('question_id', sa.BigInteger(), nullable=True),
    sa.Column('reply_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('report_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['course_questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reply_id'], ['course_question_replies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_reports_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_reports_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_reports_reply_id'), ['reply_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_reports_report_type'), ['report_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_reports_reported_user_id'), ['reported_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_reports_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_reports_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_reports_status'))
        batch_op.drop_index(batch_op.f('ix_learning_reports_reporter_id'))
        batch_op.drop_index(batch_op.f('ix_learning_reports_reported_user_id'))
        batch_op.drop_index(batch_op.f('ix_learning_reports_report_type'))
        batch_op.drop_index(batch_op.f('ix_learning_reports_reply_id'))
        batch_op.drop_index(batch_op.f('ix_learning_reports_question_id'))
        batch_op.drop_index(batch_op.f('ix_learning_reports_course_id'))

    op.drop_table('learning_reports')
    with op.batch_alter_table('proctoring_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proctoring_events_session_id'))
        batch_op.drop_index(batch_op.f('ix_proctoring_events_event_type'))

    op.drop_table('proctoring_events')
    with op.batch_alter_table('course_question_replies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_question_replies_user_id'))
        batch_op.drop_index(batch_op.f('ix_course_question_replies_question_id'))
        batch_op.drop_index(batch_op.f('ix_course_question_replies_legacy_id'))

    op.drop_table('course_question_replies')
    with op.batch_alter_table('proctoring_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proctoring_sessions_student_id'))
        batch_op.drop_index(batch_op.f('ix_proctoring_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_proctoring_sessions_session_key'))
        batch_op.drop_index(batch_op.f('ix_proctoring_sessions_exam_id'))

    op.drop_table('proctoring_sessions')
    with op.batch_alter_table('learning_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_progress_watched_date'))
        batch_op.drop_index(batch_op.f('ix_learning_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_learning_progress_course_id'))
        batch_op.drop_index(batch_op.f('ix_learning_progress_bookmarked'))

    op.drop_table('learning_progress')
    with op.batch_alter_table('exam_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_results_student_id'))
        batch_op.drop_index(batch_op.f('ix_exam_results_exam_id'))

    op.drop_table('exam_results')
    with op.batch_alter_table('exam_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_questions_exam_id'))

    op.drop_table('exam_questions')
    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_attempts_student_id'))
        batch_op.drop_index(batch_op.f('ix_exam_attempts_exam_id'))

    op.drop_table('exam_attempts')
    with op.batch_alter_table('course_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_views_user_id'))
        batch_op.drop_index(batch_op.f('ix_course_views_course_id'))

    op.drop_table('course_views')
    with op.batch_alter_table('course_saved_list_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_saved_list_items_saved_list_id'))
        batch_op.drop_index(batch_op.f('ix_course_saved_list_items_course_id'))

    op.drop_table('course_saved_list_items')
    with op.batch_alter_table('course_ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_ratings_user_id'))
        batch_op.drop_index(batch_op.f('ix_course_ratings_course_id'))

    op.drop_table('course_ratings')
    with op.batch_alter_table('course_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_questions_user_role'))
        batch_op.drop_index(batch_op.f('ix_course_questions_user_id'))
        batch_op.drop_index(batch_op.f('ix_course_questions_legacy_id'))
        batch_op.drop_index(batch_op.f('ix_course_questions_course_id'))

    op.drop_table('course_questions')
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exams_visibility'))
        batch_op.drop_index(batch_op.f('ix_exams_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_exams_subject'))
        batch_op.drop_index(batch_op.f('ix_exams_status'))

    op.drop_table('exams')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_visibility'))
        batch_op.drop_index(batch_op.f('ix_courses_teacher_subject'))
        batch_op.drop_index(batch_op.f('ix_courses_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_courses_teacher_email'))
        batch_op.drop_index(batch_op.f('ix_courses_status'))
        batch_op.drop_index(batch_op.f('ix_courses_open_at_ms'))
        batch_op.drop_index(batch_op.f('ix_courses_moderation_status'))
        batch_op.drop_index(batch_op.f('ix_courses_legacy_id'))
        batch_op.drop_index(batch_op.f('ix_courses_is_featured'))
        batch_op.drop_index(batch_op.f('ix_courses_difficulty'))
        batch_op.drop_index(batch_op.f('ix_courses_course_code'))
        batch_op.drop_index(batch_op.f('ix_courses_content_type'))
        batch_op.drop_index(batch_op.f('ix_courses_class_name'))
        batch_op.drop_index(batch_op.f('ix_courses_class_id'))
        batch_op.drop_index(batch_op.f('ix_courses_category'))

    op.drop_table('courses')
    with op.batch_alter_table('course_saved_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_saved_lists_owner_id'))

    op.drop_table('course_saved_lists')
    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_conversations_user_id'))

    op.drop_table('chat_conversations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_grade'))
        batch_op.drop_index(batch_op.f('ix_users_google_sub'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_class_name'))

    op.drop_table('users')
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classrooms_grade'))
        batch_op.drop_index(batch_op.f('ix_classrooms_class_code'))

    op.drop_table('classrooms')
    # ### end Alembic commands ###
