"""add online judge models

Revision ID: 57e8e140f469
Revises: 5d0459b03689
Create Date: 2026-09-17 12:03:02.790488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e8e140f469'
down_revision = '5d0459b03689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oj_problems',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('input_description', sa.Text(), nullable=True),
    sa.Column('output_description', sa.Text(), nullable=True),
    sa.Column('constraints_text', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('time_limit_ms', sa.Integer(), nullable=False),
    sa.Column('memory_limit_mb', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("difficulty IN ('EASY', 'MEDIUM', 'HARD')", name='ck_oj_problems_difficulty'),
    sa.CheckConstraint("status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')", name='ck_oj_problems_status'),
    sa.CheckConstraint('memory_limit_mb > 0', name='ck_oj_problems_memory_limit_positive'),
    sa.CheckConstraint('points > 0', name='ck_oj_problems_points_positive'),
    sa.CheckConstraint('time_limit_ms > 0', name='ck_oj_problems_time_limit_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oj_problems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oj_problems_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_oj_problems_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_oj_problems_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_oj_problems_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_oj_problems_status'), ['status'], unique=False)

    op.create_table('oj_submissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('problem_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('language', sa.String(length=30), nullable=False),
    sa.Column('source_code', sa.Text(), nullable=False),
    sa.Column('verdict', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('memory_used_kb', sa.BigInteger(), nullable=True),
    sa.Column('compiler_output', sa.Text(), nullable=True),
    sa.Column('judge_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('judged_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("language IN ('CPP23', 'PYTHON314', 'JAVA21')", name='ck_oj_submissions_language'),
    sa.CheckConstraint("verdict IN ('PENDING', 'JUDGING', 'AC', 'WA', 'TLE', 'MLE', 'RE', 'CE', 'IE')", name='ck_oj_submissions_verdict'),
    sa.ForeignKeyConstraint(['problem_id'], ['oj_problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oj_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oj_submissions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_oj_submissions_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_oj_submissions_problem_id'), ['problem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oj_submissions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oj_submissions_verdict'), ['verdict'], unique=False)

    op.create_table('oj_testcases',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('problem_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=False),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['oj_problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_id', 'position', name='uq_oj_testcase_position')
    )
    with op.batch_alter_table('oj_testcases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oj_testcases_is_sample'), ['is_sample'], unique=False)
        batch_op.create_index(batch_op.f('ix_oj_testcases_problem_id'), ['problem_id'], unique=False)

    op.create_table('oj_submission_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.BigInteger(), nullable=False),
    sa.Column('testcase_id', sa.BigInteger(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=30), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('memory_used_kb', sa.BigInteger(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['oj_submissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['testcase_id'], ['oj_testcases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'position', name='uq_oj_submission_result_position')
    )
    with op.batch_alter_table('oj_submission_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oj_submission_results_submission_id'), ['submission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oj_submission_results_testcase_id'), ['testcase_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oj_submission_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oj_submission_results_testcase_id'))
        batch_op.drop_index(batch_op.f('ix_oj_submission_results_submission_id'))

    op.drop_table('oj_submission_results')
    with op.batch_alter_table('oj_testcases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oj_testcases_problem_id'))
        batch_op.drop_index(batch_op.f('ix_oj_testcases_is_sample'))

    op.drop_table('oj_testcases')
    with op.batch_alter_table('oj_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oj_submissions_verdict'))
        batch_op.drop_index(batch_op.f('ix_oj_submissions_user_id'))
        batch_op.drop_index(batch_op.f('ix_oj_submissions_problem_id'))
        batch_op.drop_index(batch_op.f('ix_oj_submissions_language'))
        batch_op.drop_index(batch_op.f('ix_oj_submissions_created_at'))

    op.drop_table('oj_submissions')
    with op.batch_alter_table('oj_problems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oj_problems_status'))
        batch_op.drop_index(batch_op.f('ix_oj_problems_difficulty'))
        batch_op.drop_index(batch_op.f('ix_oj_problems_created_by'))
        batch_op.drop_index(batch_op.f('ix_oj_problems_code'))
        batch_op.drop_index(batch_op.f('ix_oj_problems_category'))

    op.drop_table('oj_problems')
    # ### end Alembic commands ###
