"""upgrade classroom sql

Revision ID: 5d0459b03689
Revises: 1b9137dfd4ac
Create Date: 2026-08-25 22:59:22.198820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d0459b03689'
down_revision = '1b9137dfd4ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom_assignments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=255), nullable=True),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at_ms', sa.BigInteger(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('assignment_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classroom_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classroom_assignments_classroom_id'), ['classroom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_assignments_due_at_ms'), ['due_at_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_assignments_legacy_id'), ['legacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_assignments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_assignments_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('classroom_attendance',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('attendance_date', sa.String(length=20), nullable=False),
    sa.Column('teacher_id', sa.BigInteger(), nullable=True),
    sa.Column('records', sa.JSON(), nullable=True),
    sa.Column('intern_records', sa.JSON(), nullable=True),
    sa.Column('qr_check_ins', sa.JSON(), nullable=True),
    sa.Column('qr_token', sa.String(length=255), nullable=True),
    sa.Column('qr_expires_at_ms', sa.BigInteger(), nullable=True),
    sa.Column('qr_created_by', sa.BigInteger(), nullable=True),
    sa.Column('qr_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('present_count', sa.Integer(), nullable=True),
    sa.Column('late_count', sa.Integer(), nullable=True),
    sa.Column('absent_count', sa.Integer(), nullable=True),
    sa.Column('excused_count', sa.Integer(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('attendance_rate', sa.Float(), nullable=True),
    sa.Column('attendance_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classroom_id', 'attendance_date', name='uq_classroom_attendance_date')
    )
    with op.batch_alter_table('classroom_attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classroom_attendance_attendance_date'), ['attendance_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_attendance_classroom_id'), ['classroom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_attendance_qr_expires_at_ms'), ['qr_expires_at_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_attendance_qr_token'), ['qr_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_attendance_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('classroom_members',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=255), nullable=True),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('class_role', sa.String(length=50), nullable=True),
    sa.Column('student_code', sa.String(length=100), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('birth_date', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('parent_name', sa.String(length=255), nullable=True),
    sa.Column('parent_phone', sa.String(length=100), nullable=True),
    sa.Column('parent_email', sa.String(length=255), nullable=True),
    sa.Column('parent_relation', sa.String(length=100), nullable=True),
    sa.Column('medical_note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('member_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classroom_members', schema=None) as batch_op:
        batch_op.create_index('ix_classroom_members_class_email', ['classroom_id', 'email'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_members_class_role'), ['class_role'], unique=False)
        batch_op.create_index('ix_classroom_members_class_user', ['classroom_id', 'user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_members_classroom_id'), ['classroom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_members_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_members_legacy_id'), ['legacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_members_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_members_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_members_student_code'), ['student_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_members_user_id'), ['user_id'], unique=False)

    op.create_table('classroom_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=255), nullable=True),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=500), nullable=True),
    sa.Column('sender_id', sa.BigInteger(), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=True),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('sender_avatar', sa.Text(), nullable=True),
    sa.Column('receiver_id', sa.BigInteger(), nullable=True),
    sa.Column('receiver_email', sa.String(length=255), nullable=True),
    sa.Column('receiver_name', sa.String(length=255), nullable=True),
    sa.Column('receiver_type', sa.String(length=100), nullable=True),
    sa.Column('receiver_avatar', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('attachment', sa.JSON(), nullable=True),
    sa.Column('recalled', sa.Boolean(), nullable=True),
    sa.Column('recalled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classroom_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classroom_messages_classroom_id'), ['classroom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_messages_legacy_id'), ['legacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_messages_recalled'), ['recalled'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_messages_receiver_email'), ['receiver_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_messages_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_messages_sender_email'), ['sender_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_messages_sender_id'), ['sender_id'], unique=False)

    op.create_table('classroom_notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=255), nullable=True),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=500), nullable=True),
    sa.Column('notification_type', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('notification_kind', sa.String(length=100), nullable=True),
    sa.Column('system_generated', sa.Boolean(), nullable=True),
    sa.Column('automatic_label', sa.String(length=255), nullable=True),
    sa.Column('recipient_type', sa.String(length=100), nullable=True),
    sa.Column('recipient_uid', sa.BigInteger(), nullable=True),
    sa.Column('recipient_email', sa.String(length=255), nullable=True),
    sa.Column('recipient_student_id', sa.BigInteger(), nullable=True),
    sa.Column('author_id', sa.BigInteger(), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('read_by', sa.JSON(), nullable=True),
    sa.Column('dismissed_by', sa.JSON(), nullable=True),
    sa.Column('notification_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classroom_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classroom_notifications_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_notifications_classroom_id'), ['classroom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_notifications_legacy_id'), ['legacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_notifications_notification_kind'), ['notification_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_notifications_notification_type'), ['notification_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_notifications_recipient_email'), ['recipient_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_notifications_recipient_student_id'), ['recipient_student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_notifications_recipient_type'), ['recipient_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_notifications_recipient_uid'), ['recipient_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_notifications_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_notifications_source_key'), ['source_key'], unique=False)

    op.create_table('classroom_schedule',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=255), nullable=True),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.BigInteger(), nullable=True),
    sa.Column('week_key', sa.String(length=50), nullable=True),
    sa.Column('schedule_date', sa.String(length=20), nullable=True),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.String(length=20), nullable=True),
    sa.Column('end_time', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('lesson_content', sa.Text(), nullable=True),
    sa.Column('room', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('important', sa.Boolean(), nullable=True),
    sa.Column('kind', sa.String(length=100), nullable=True),
    sa.Column('expires_at_ms', sa.BigInteger(), nullable=True),
    sa.Column('schedule_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classroom_schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classroom_schedule_classroom_id'), ['classroom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_schedule_expires_at_ms'), ['expires_at_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_schedule_important'), ['important'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_schedule_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_schedule_legacy_id'), ['legacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_schedule_schedule_date'), ['schedule_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_schedule_teacher_id'), ['teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_schedule_week_key'), ['week_key'], unique=False)

    op.create_table('classroom_subjects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=255), nullable=True),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('subject_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classroom_subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classroom_subjects_classroom_id'), ['classroom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_subjects_legacy_id'), ['legacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_subjects_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('classroom_attendance_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('attendance_id', sa.BigInteger(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('attendance_date', sa.String(length=20), nullable=False),
    sa.Column('teacher_id', sa.BigInteger(), nullable=True),
    sa.Column('teacher_name', sa.String(length=255), nullable=True),
    sa.Column('teacher_email', sa.String(length=255), nullable=True),
    sa.Column('records', sa.JSON(), nullable=True),
    sa.Column('present_count', sa.Integer(), nullable=True),
    sa.Column('late_count', sa.Integer(), nullable=True),
    sa.Column('absent_count', sa.Integer(), nullable=True),
    sa.Column('excused_count', sa.Integer(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('attendance_rate', sa.Float(), nullable=True),
    sa.Column('history_data', sa.JSON(), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['classroom_attendance.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classroom_attendance_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classroom_attendance_history_attendance_date'), ['attendance_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_attendance_history_attendance_id'), ['attendance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_attendance_history_classroom_id'), ['classroom_id'], unique=False)

    op.create_table('classroom_scores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('scores', sa.JSON(), nullable=True),
    sa.Column('average', sa.Float(), nullable=True),
    sa.Column('score_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['classroom_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['classroom_subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'member_id', name='uq_classroom_score_subject_member')
    )
    with op.batch_alter_table('classroom_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classroom_scores_classroom_id'), ['classroom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_scores_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_scores_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_scores_user_id'), ['user_id'], unique=False)

    op.create_table('classroom_subject_tests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.String(length=255), nullable=True),
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('test_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['classroom_subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classroom_subject_tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classroom_subject_tests_classroom_id'), ['classroom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_subject_tests_legacy_id'), ['legacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_subject_tests_subject_id'), ['subject_id'], unique=False)

    op.create_table('classroom_submissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.BigInteger(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('student_name', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('attachment', sa.JSON(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_late', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('submission_data', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['classroom_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['classroom_members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classroom_submissions', schema=None) as batch_op:
        batch_op.create_index('ix_classroom_submission_assignment_member', ['assignment_id', 'member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_submissions_assignment_id'), ['assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_submissions_classroom_id'), ['classroom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_submissions_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_submissions_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_submissions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_classroom_submissions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('teacher_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('teacher_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('teacher_photo_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('teacher_gender', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('school', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('subject', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('school_year', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('theme_color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cover_photo_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('logo_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('student_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('member_ids', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('dismissed_notification_source_keys', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('schedule_week_configs', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('schedule_time_rules', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('schedule_content_rules', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('class_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_classrooms_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_classrooms_teacher_email'), ['teacher_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_classrooms_teacher_id'), ['teacher_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['teacher_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_classrooms_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_classrooms_teacher_email'))
        batch_op.drop_index(batch_op.f('ix_classrooms_status'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('class_data')
        batch_op.drop_column('schedule_content_rules')
        batch_op.drop_column('schedule_time_rules')
        batch_op.drop_column('schedule_week_configs')
        batch_op.drop_column('dismissed_notification_source_keys')
        batch_op.drop_column('member_ids')
        batch_op.drop_column('student_count')
        batch_op.drop_column('status')
        batch_op.drop_column('logo_url')
        batch_op.drop_column('cover_photo_url')
        batch_op.drop_column('theme_color')
        batch_op.drop_column('school_year')
        batch_op.drop_column('subject')
        batch_op.drop_column('school')
        batch_op.drop_column('teacher_gender')
        batch_op.drop_column('teacher_photo_url')
        batch_op.drop_column('teacher_name')
        batch_op.drop_column('teacher_email')
        batch_op.drop_column('teacher_id')

    with op.batch_alter_table('classroom_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classroom_submissions_user_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_submissions_status'))
        batch_op.drop_index(batch_op.f('ix_classroom_submissions_member_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_submissions_email'))
        batch_op.drop_index(batch_op.f('ix_classroom_submissions_classroom_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_submissions_assignment_id'))
        batch_op.drop_index('ix_classroom_submission_assignment_member')

    op.drop_table('classroom_submissions')
    with op.batch_alter_table('classroom_subject_tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classroom_subject_tests_subject_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_subject_tests_legacy_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_subject_tests_classroom_id'))

    op.drop_table('classroom_subject_tests')
    with op.batch_alter_table('classroom_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classroom_scores_user_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_scores_subject_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_scores_member_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_scores_classroom_id'))

    op.drop_table('classroom_scores')
    with op.batch_alter_table('classroom_attendance_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classroom_attendance_history_classroom_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_attendance_history_attendance_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_attendance_history_attendance_date'))

    op.drop_table('classroom_attendance_history')
    with op.batch_alter_table('classroom_subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classroom_subjects_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_subjects_legacy_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_subjects_classroom_id'))

    op.drop_table('classroom_subjects')
    with op.batch_alter_table('classroom_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classroom_schedule_week_key'))
        batch_op.drop_index(batch_op.f('ix_classroom_schedule_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_schedule_schedule_date'))
        batch_op.drop_index(batch_op.f('ix_classroom_schedule_legacy_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_schedule_kind'))
        batch_op.drop_index(batch_op.f('ix_classroom_schedule_important'))
        batch_op.drop_index(batch_op.f('ix_classroom_schedule_expires_at_ms'))
        batch_op.drop_index(batch_op.f('ix_classroom_schedule_classroom_id'))

    op.drop_table('classroom_schedule')
    with op.batch_alter_table('classroom_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classroom_notifications_source_key'))
        batch_op.drop_index(batch_op.f('ix_classroom_notifications_severity'))
        batch_op.drop_index(batch_op.f('ix_classroom_notifications_recipient_uid'))
        batch_op.drop_index(batch_op.f('ix_classroom_notifications_recipient_type'))
        batch_op.drop_index(batch_op.f('ix_classroom_notifications_recipient_student_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_notifications_recipient_email'))
        batch_op.drop_index(batch_op.f('ix_classroom_notifications_notification_type'))
        batch_op.drop_index(batch_op.f('ix_classroom_notifications_notification_kind'))
        batch_op.drop_index(batch_op.f('ix_classroom_notifications_legacy_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_notifications_classroom_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_notifications_author_id'))

    op.drop_table('classroom_notifications')
    with op.batch_alter_table('classroom_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classroom_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_messages_sender_email'))
        batch_op.drop_index(batch_op.f('ix_classroom_messages_receiver_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_messages_receiver_email'))
        batch_op.drop_index(batch_op.f('ix_classroom_messages_recalled'))
        batch_op.drop_index(batch_op.f('ix_classroom_messages_legacy_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_classroom_messages_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_messages_classroom_id'))

    op.drop_table('classroom_messages')
    with op.batch_alter_table('classroom_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classroom_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_members_student_code'))
        batch_op.drop_index(batch_op.f('ix_classroom_members_status'))
        batch_op.drop_index(batch_op.f('ix_classroom_members_role'))
        batch_op.drop_index(batch_op.f('ix_classroom_members_legacy_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_members_email'))
        batch_op.drop_index(batch_op.f('ix_classroom_members_classroom_id'))
        batch_op.drop_index('ix_classroom_members_class_user')
        batch_op.drop_index(batch_op.f('ix_classroom_members_class_role'))
        batch_op.drop_index('ix_classroom_members_class_email')

    op.drop_table('classroom_members')
    with op.batch_alter_table('classroom_attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classroom_attendance_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_attendance_qr_token'))
        batch_op.drop_index(batch_op.f('ix_classroom_attendance_qr_expires_at_ms'))
        batch_op.drop_index(batch_op.f('ix_classroom_attendance_classroom_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_attendance_attendance_date'))

    op.drop_table('classroom_attendance')
    with op.batch_alter_table('classroom_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classroom_assignments_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_assignments_status'))
        batch_op.drop_index(batch_op.f('ix_classroom_assignments_legacy_id'))
        batch_op.drop_index(batch_op.f('ix_classroom_assignments_due_at_ms'))
        batch_op.drop_index(batch_op.f('ix_classroom_assignments_classroom_id'))

    op.drop_table('classroom_assignments')
    # ### end Alembic commands ###
