"""upgrade forum group chat sql

Revision ID: 5e5c85f48480
Revises: 5eb3836483b9
Create Date: 2026-08-24 21:08:02.982066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5c85f48480'
down_revision = '5eb3836483b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_group_presence',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.String(length=120), nullable=False),
    sa.Column('channel_label', sa.String(length=255), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['forum_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_forum_group_presence_group_user')
    )
    with op.batch_alter_table('forum_group_presence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_group_presence_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_group_presence_last_seen'), ['last_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_group_presence_online'), ['online'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_group_presence_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('forum_group_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_id', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('message_type', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('is_announcement', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_like', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('attachment_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('attachment_key', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('attachment_name', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('attachment_type', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('attachment_size', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('reply_to_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('reply_to_author', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reply_to_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reactions', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('is_pinned', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('edited', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('metadata_json', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.create_index(batch_op.f('ix_forum_group_messages_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_group_messages_is_pinned'), ['is_pinned'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_group_messages_message_type'), ['message_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_group_messages_reply_to_id'), ['reply_to_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_group_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_group_messages_reply_to_id'))
        batch_op.drop_index(batch_op.f('ix_forum_group_messages_message_type'))
        batch_op.drop_index(batch_op.f('ix_forum_group_messages_is_pinned'))
        batch_op.drop_index(batch_op.f('ix_forum_group_messages_channel_id'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('metadata_json')
        batch_op.drop_column('edited_at')
        batch_op.drop_column('edited')
        batch_op.drop_column('is_pinned')
        batch_op.drop_column('reactions')
        batch_op.drop_column('reply_to_content')
        batch_op.drop_column('reply_to_author')
        batch_op.drop_column('reply_to_id')
        batch_op.drop_column('attachment_size')
        batch_op.drop_column('attachment_type')
        batch_op.drop_column('attachment_name')
        batch_op.drop_column('attachment_key')
        batch_op.drop_column('attachment_url')
        batch_op.drop_column('is_like')
        batch_op.drop_column('is_announcement')
        batch_op.drop_column('message_type')
        batch_op.drop_column('channel_id')

    with op.batch_alter_table('forum_group_presence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_group_presence_user_id'))
        batch_op.drop_index(batch_op.f('ix_forum_group_presence_online'))
        batch_op.drop_index(batch_op.f('ix_forum_group_presence_last_seen'))
        batch_op.drop_index(batch_op.f('ix_forum_group_presence_group_id'))

    op.drop_table('forum_group_presence')
    # ### end Alembic commands ###
