"""add forum groups sql models

Revision ID: 5eb3836483b9
Revises: 1e7237cbec13
Create Date: 2026-08-24 20:04:27.710895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb3836483b9'
down_revision = '1e7237cbec13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_groups',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('group_type', sa.String(length=30), nullable=False),
    sa.Column('group_code', sa.String(length=32), nullable=False),
    sa.Column('invite_code', sa.String(length=128), nullable=True),
    sa.Column('member_ids', sa.JSON(), nullable=False),
    sa.Column('admin_ids', sa.JSON(), nullable=False),
    sa.Column('pending_member_ids', sa.JSON(), nullable=False),
    sa.Column('temporary_admin_ids', sa.JSON(), nullable=False),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.Column('report_status', sa.String(length=30), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forum_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_groups_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_groups_group_code'), ['group_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_forum_groups_group_type'), ['group_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_groups_invite_code'), ['invite_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_forum_groups_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_groups_report_status'), ['report_status'], unique=False)

    op.create_table('forum_group_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['forum_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forum_group_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_group_messages_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_group_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_group_messages_group_id'), ['group_id'], unique=False)

    op.create_table('forum_group_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('reporter_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resolved_by', sa.BigInteger(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['forum_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'reporter_id', 'status', name='uq_forum_group_report_open_user')
    )
    with op.batch_alter_table('forum_group_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_group_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_group_reports_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_group_reports_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_group_reports_status'), ['status'], unique=False)

    op.create_table('forum_group_warnings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('report_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['forum_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forum_group_warnings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_group_warnings_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_group_warnings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_group_warnings_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_group_warnings_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_group_warnings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_group_warnings_owner_id'))
        batch_op.drop_index(batch_op.f('ix_forum_group_warnings_group_id'))
        batch_op.drop_index(batch_op.f('ix_forum_group_warnings_created_at'))
        batch_op.drop_index(batch_op.f('ix_forum_group_warnings_admin_id'))

    op.drop_table('forum_group_warnings')
    with op.batch_alter_table('forum_group_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_group_reports_status'))
        batch_op.drop_index(batch_op.f('ix_forum_group_reports_reporter_id'))
        batch_op.drop_index(batch_op.f('ix_forum_group_reports_group_id'))
        batch_op.drop_index(batch_op.f('ix_forum_group_reports_created_at'))

    op.drop_table('forum_group_reports')
    with op.batch_alter_table('forum_group_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_group_messages_group_id'))
        batch_op.drop_index(batch_op.f('ix_forum_group_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_forum_group_messages_author_id'))

    op.drop_table('forum_group_messages')
    with op.batch_alter_table('forum_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_groups_report_status'))
        batch_op.drop_index(batch_op.f('ix_forum_groups_owner_id'))
        batch_op.drop_index(batch_op.f('ix_forum_groups_invite_code'))
        batch_op.drop_index(batch_op.f('ix_forum_groups_group_type'))
        batch_op.drop_index(batch_op.f('ix_forum_groups_group_code'))
        batch_op.drop_index(batch_op.f('ix_forum_groups_created_at'))

    op.drop_table('forum_groups')
    # ### end Alembic commands ###
