"""extend forum post fields

Revision ID: be588aa4e89a
Revises: c45b57eae566
Create Date: 2026-08-24 16:02:00.407361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be588aa4e89a'
down_revision = 'c45b57eae566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('group_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('group_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('attachment_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('attachment_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('event_start_at', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('event_end_at', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('event_location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('event_created_by_admin', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('event_interested_by', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('event_not_interested_by', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('event_started_notified_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('event_ended_notified_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('poll_options', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('poll_start_at', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('poll_end_at', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('poll_votes', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('poll_votes_count', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('moderation_status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('rejected_by', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('author_name_override', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('author_email_override', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('author_initials_override', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('author_photo_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('author_role_override', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('likes_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('reactions_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('reaction_counts', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('reactions', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('liked_by', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('views_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('viewed_by', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('saved_by', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('is_pinned', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_anonymous', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_answered', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('report_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('reported_by', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('report_status', sa.String(length=30), nullable=True))
        batch_op.create_index(batch_op.f('ix_forum_posts_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_posts_moderation_status'), ['moderation_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_posts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_posts_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_posts_type'))
        batch_op.drop_index(batch_op.f('ix_forum_posts_status'))
        batch_op.drop_index(batch_op.f('ix_forum_posts_moderation_status'))
        batch_op.drop_index(batch_op.f('ix_forum_posts_group_id'))
        batch_op.drop_column('report_status')
        batch_op.drop_column('reported_by')
        batch_op.drop_column('report_count')
        batch_op.drop_column('is_answered')
        batch_op.drop_column('is_anonymous')
        batch_op.drop_column('is_pinned')
        batch_op.drop_column('saved_by')
        batch_op.drop_column('viewed_by')
        batch_op.drop_column('views_count')
        batch_op.drop_column('liked_by')
        batch_op.drop_column('reactions')
        batch_op.drop_column('reaction_counts')
        batch_op.drop_column('reactions_count')
        batch_op.drop_column('likes_count')
        batch_op.drop_column('author_role_override')
        batch_op.drop_column('author_photo_url')
        batch_op.drop_column('author_initials_override')
        batch_op.drop_column('author_email_override')
        batch_op.drop_column('author_name_override')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('rejected_at')
        batch_op.drop_column('rejected_by')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('moderation_status')
        batch_op.drop_column('status')
        batch_op.drop_column('poll_votes_count')
        batch_op.drop_column('poll_votes')
        batch_op.drop_column('poll_end_at')
        batch_op.drop_column('poll_start_at')
        batch_op.drop_column('poll_options')
        batch_op.drop_column('event_ended_notified_at')
        batch_op.drop_column('event_started_notified_at')
        batch_op.drop_column('event_not_interested_by')
        batch_op.drop_column('event_interested_by')
        batch_op.drop_column('event_created_by_admin')
        batch_op.drop_column('event_location')
        batch_op.drop_column('event_end_at')
        batch_op.drop_column('event_start_at')
        batch_op.drop_column('image_url')
        batch_op.drop_column('attachment_name')
        batch_op.drop_column('attachment_url')
        batch_op.drop_column('group_name')
        batch_op.drop_column('group_id')
        batch_op.drop_column('tags')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
