"""add forum sql models

Revision ID: c45b57eae566
Revises: 2fac5d8cc903
Create Date: 2026-08-24 15:35:18.784805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c45b57eae566'
down_revision = '2fac5d8cc903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_posts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('teacher_only', sa.Boolean(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_posts_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_posts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_posts_scope'), ['scope'], unique=False)

    op.create_table('forum_comments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('root_comment_id', sa.BigInteger(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('reactions_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['forum_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['forum_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forum_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_comments_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_comments_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_comments_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_comments_root_comment_id'), ['root_comment_id'], unique=False)

    op.create_table('forum_comment_reactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('comment_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('reaction', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['forum_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'user_id', name='uq_forum_comment_reactions_comment_user')
    )
    with op.batch_alter_table('forum_comment_reactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_comment_reactions_comment_id'), ['comment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_comment_reactions_user_id'), ['user_id'], unique=False)

    op.create_table('forum_notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('to_user_id', sa.BigInteger(), nullable=False),
    sa.Column('from_user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=True),
    sa.Column('comment_id', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['forum_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['forum_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forum_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_notifications_comment_id'), ['comment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_notifications_from_user_id'), ['from_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_notifications_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_notifications_read'), ['read'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_notifications_to_user_id'), ['to_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_notifications_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_notifications_type'))
        batch_op.drop_index(batch_op.f('ix_forum_notifications_to_user_id'))
        batch_op.drop_index(batch_op.f('ix_forum_notifications_read'))
        batch_op.drop_index(batch_op.f('ix_forum_notifications_post_id'))
        batch_op.drop_index(batch_op.f('ix_forum_notifications_from_user_id'))
        batch_op.drop_index(batch_op.f('ix_forum_notifications_created_at'))
        batch_op.drop_index(batch_op.f('ix_forum_notifications_comment_id'))

    op.drop_table('forum_notifications')
    with op.batch_alter_table('forum_comment_reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_comment_reactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_forum_comment_reactions_comment_id'))

    op.drop_table('forum_comment_reactions')
    with op.batch_alter_table('forum_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_comments_root_comment_id'))
        batch_op.drop_index(batch_op.f('ix_forum_comments_post_id'))
        batch_op.drop_index(batch_op.f('ix_forum_comments_parent_id'))
        batch_op.drop_index(batch_op.f('ix_forum_comments_created_at'))
        batch_op.drop_index(batch_op.f('ix_forum_comments_author_id'))

    op.drop_table('forum_comments')
    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_posts_scope'))
        batch_op.drop_index(batch_op.f('ix_forum_posts_created_at'))
        batch_op.drop_index(batch_op.f('ix_forum_posts_author_id'))

    op.drop_table('forum_posts')
    # ### end Alembic commands ###
